development:
  adapter: postgresql
  encoding: unicode
  database: soil_development
  pool: 5
  username: ffeldhaus
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: soil_test
  pool: 5
  username: ffeldhaus
  password:

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: soil_production
  pool: 5
  username: ffeldhaus
  password: